### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by nagarjunsanji** [debricked/VS-Code-extension#41]
### Feature Title

Sentry integration

### Description

As a developer, we need to monitor potential bugs and problems with the extension. Therefore, we should log errors to sentry to continuously monitor for regressions and new buggs.

### Task

* [ ] Integrate to sentry in a secure way. Talk to Linus about the security requirements of the integration.
* [ ] Ensure that we do not log sensitive information (to sentry & the .log file)
* [ ] Enable users to opt out of sentry logging
* [ ] Log all uncaught exceptions to sentry (Should be a simple configuration)
* [ ] Setup breadcrumb logging as context to exceptions

### Acceptance Criteria

NA
