### ISSUE TITLE
Integrate Debricked CLI with VS Code Extension

### ISSUE THREAD

**Issue by nagarjunsanji** [debricked/VS-Code-extension#6]
### Feature Title

Integrate Debricked CLI with VS Code Extension

### Description

**Tasks:**

1. Discuss with Oscar about the integration and release process. Should we lock it to a tag? etc..
2. Include Debricked CLI as part of the extension package and agree on where it should be installed with Oscar.
3. Ensure the CLI is executable from within the extension.
4. Write helper functions to interact with the CLI.
5. Update documentation to reflect the new integration.

**Acceptance Criteria:**

* [ ] Debricked CLI is included and functional within the extension. It should probably be downloaded from the source (https://github.com/debricked/cli/releases) during installation
* [ ] Linux/windows/mac/wsl users install the correct distribution of the CLI.
* [ ] The CLI is updated when we update the extension.

### Motivation

As a developer, I want to integrate the Debricked CLI with the VS Code extension to provide additional functionalities to the extension users.
